export const AUTH_LOGIN_REJECTED = 'AUTH_LOGIN_REJECTED'
export const AUTH_LOGIN_FULFILLED = 'AUTH_LOGIN_FULFILLED'
export const AUTH_REGISTER_FULFILLED = 'AUTH_REGISTER_FULFILLED'
export const AUTH_REGISTER_REJECTED = 'AUTH_REGISTER_REJECTED'
export const USER_SET_DATA = 'USER_SET_DATA'

export const VIDEOS_REQUEST_PENDING = 'VIDEOS_REQUEST_PENDING'
export const VIDEOS_REQUEST_REJECTED = 'VIDEOS_REQUEST_REJECTED'
export const VIDEOS_REQUEST_FULFILLED = 'VIDEOS_REQUEST_FULFILLED'
